---
- hosts: web
  vars:
    - download_file: https://download.java.net/java/GA/jdk10/10.0.1/fb4372174a714e6b8c52526dc134031e/10/openjdk-10.0.1_linux-x64_bin.tar.gz
  tasks:
    - name: create java folder
      file: path=/opt/java state=directory
    - name: download java file
      get_url: url={{download_file}} dest=/opt/java/
    - name: unzip downloaded java file
      unarchive: src=/opt/java/openjdk-10.0.1_linux-x64_bin.tar.gz dest=/opt/java remote_src=yes
    - name: create sym links
      file: path="/opt/java/current" src=/opt/java state=link
    - name: create profile file
      file: path=~/.profile state=touch
    - name: add java variable
      lineinfile: path=~/.profile line='export JAVA_HOME=/opt/java/jdk-10.0.1'
      lineinfile: path=~/.profile line='export PATH=$JAVA_HOME/bin:$PATH'
    - name: update variable file
      shell: source ~/.profile
